### ISSUE TITLE
[client] feature /  참가 신청 팝업 화면 만들기

### ISSUE THREAD

**Issue by Ma-SangHee** [codestates/JOINUS-client#15]
### ISSUE
- Group:  `client`
- Type:  `feature`, 
- Detail: 참가 신청 팝업 화면 만들기

### TODO
1. [x] 목업 화면과 같이 구성
2. [x] 프로젝트 세부 페이지 에서 참가 버튼을 누르면 참가 신청 화면으로 이동하기 
3. [x] fake Data 만들기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
