### ISSUE TITLE
[client] feature / 네비게이션 & 로고 및 파비콘 제작

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#17]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: (상시 노출) 네비게이션 제작

### TODO
1. [x] (임시) 메인 페이지 연결
3. [x] 로그인 / 회원 가입 레이아웃
2. [x] 로고 / 파비콘 제작
4. [x] 검색 컴포넌트 추가

### Estimated time
- `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-2`
- Urgency: `Middle`
