### ISSUE TITLE
[client] feature / 이메일 로그인 기능 구현

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#20]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인 기능 구현

### TODO
1. [x] 레이아웃 구성
1. [x] (테스트용)로그인 관련 리덕스 상태 / 액션 / 리듀서 추가
2. [x] 로그인 유효성 검사 구현
3. [x] 로그인 후 토큰 / 유저 정보 처리 구상

### Estimated time
- 3h

### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `3-2`
- Urgency: `High`
