### ISSUE TITLE
[client] feature / 마이페이지 '신청한 목록' 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by stepperweb** [codestates/JOINUS-client#22]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: project requirement에 따른 모달기능 구현

### TODO
1. [x] 레이아웃 및 기능 구현
2. [x] fakedata에 나오는 지원한 유저정보 조회가능
3. [x] fakedata 에 나오는 유저정보 삭제 가능
4. [x] fakedata 에 나오는 유저정보 수락 가능

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-1`
- Urgency: `High`
