### ISSUE TITLE
[client] feature / 메인 페이지 필터링 컴포넌트 작성

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#25]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 필터링 컴포넌트 작성

### TODO
1. [x] 레이아웃 구성
2. [x] 태그 클릭 / 해제 효과 구현
3. [x] 필터링 기능 구현
4. [x] 필터링에 따른 화면 출력 구성
5. [x] 데이터 재사용을 위한 가공

### Estimated time
- `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-2`
- Urgency: `High`
