### ISSUE TITLE
[client] feature / 참가하기 기능 연결하기 

### ISSUE THREAD

**Issue by Ma-SangHee** [codestates/JOINUS-client#26]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 세부페이지에서 참가하기 버튼 클릭 했을 때 기능 연결 하기 

### TODO
1. [ ] 참가하기 버튼 클릭 시 참가하기 페이지로 이동하기 
2. [ ] 참가하기 페이지 기능 구현 하기(서버와 연결하기)
3. [ ] 참가 신청 후 세부 페이지로 이동. 참가하기 버튼 -> 수정 /  취소 버튼으로 변경 하기 

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: 
- Urgency: `High`
