### ISSUE TITLE
[client] feature / 이메일 로그인 테스트

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#27]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 임시 DB 생성 및 로그인 테스트

### TODO
1. [x] 임시 회원 DB 구축(로컬 혹은 EC2)
2. [x] 로그인 테스트(비동기)
3. [ ] ~상황에 따라 thunk 등 도입 고려~

### Estimated time
- `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-2`
- Urgency: `High`
