### ISSUE TITLE
[client] feature/마이페이지 페이지 전체 구현

### ISSUE THREAD

**Issue by stepperweb** [codestates/JOINUS-client#28]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: 마이페이지 전체 컴포넌트를 완성하고 이후에 페이지 전체 구현하기

### TODO
1. [x] 목업 참조하여 전체 레이아웃틀 완성하기 fakedata로돌려보기 
2. [x] 간단한 CSS 완성하기
3. [x] 각각의 컴포넌트를 하나의 페이지에 연결(props, state)
4. [x] 전체  페이지 구성 검사하기
5. [ ] fakedata 유저정보 삭제 및 수정이 가능한지 확인
6. [ ] 서버와 연결하기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `#3-1, #3-2`
- Urgency: `High`
