### ISSUE TITLE
[client] feature/ 마이페이지 전체 기능 검사

### ISSUE THREAD

**Issue by stepperweb** [codestates/JOINUS-client#31]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 레이아웃 및 기능이 완성된 페이지에 실제 서버및 DB연결 기능이 구현되는지 확인하기

### TODO
1. [ ] 임시 DB 유저의 정보 구현 
2. [ ] fakedata에 유저정보가 임시 유저의 정보로 구현
3. [ ] 전체적 기능이 잘 되는지 확인하기(정보 조회 및 수정 삭제가 가능한지)

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
