### ISSUE TITLE
[client] feature / 로그아웃 버튼 기능 구현

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#34]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그아웃 버튼 기능 구현

### TODO
1. [x] 서버 API 로그아웃 요청
2. [x] 유저정보 상태 변경
3. [x] 메인 페이지 이동
4. [x] 토큰 로그아웃 파트 구현

### Estimated time
- `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-3`
- Urgency: `High`
