### ISSUE TITLE
[client] feature / 회원가입 페이지 부가기능

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#40]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 스택 항목 자동완성, 가입완료시 모달창

### TODO
1. [x] 스택 종류 리서치 
    ![image](https://user-images.githubusercontent.com/8604840/111944702-9aa7d400-8b1b-11eb-91a8-2f2d14abf7f9.png)
2. [ ] 스택 항목 자동완성
2. [x] 가입 완료시 모달창 

### Estimated time
- `3h`

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-2`
- Urgency: `Middle`
