### ISSUE TITLE
[client] feature / 필터링 렌더 기능 구현 & 메인 페이지 프로젝트 리스트 스타일 수정

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#49]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 메인 페이지 카테고리(필터링) 개발 언어 클릭시 해당하는 언어의 프로젝트 실시간 렌더링

### TODO
1. [x] 클릭한 언어 / 서버 프로젝트 리스트에 저장된 언어 매칭 함수 작성
2. [x] 모든 프로젝트 컴포넌트 렌더 일부 수정 
3. [x] 매칭하는 프로젝트 없을 시 화면 안내 기능 
4. [x] 메인 페이지 프로젝트 리스트 스타일 수정

### Estimated time
> Pick one
`4h`

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `3-3`
- Urgency: `High`
