### ISSUE TITLE
[client] deploy / 클라이언트 배포 테스트

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#50]
### ISSUE
- Group:  `client`
- Type: `deploy`
- Detail: 클라이언트 AWS 배포 테스트

### TODO
1. [x] 버킷 생성, build 폴더 업로드
2. [x] 인증서 및 CloudFront 적용
3. [x] 라우터 수정
4. [x] 서버 통신 테스트(이메일/소셜 로그인/로그아웃/마이페이지/프로젝트 리스트 등)

### Estimated time
> Pick one
- `1.5h`

### Labels
- Estimated time: `E: 1.5h`
- Group : `client`
- Sprint: `3-3`
- Urgency: `High`
