### ISSUE TITLE
[client] feature / 개발 환경 구축 및 임시 메인 페이지 작성

### ISSUE THREAD

**Issue by romantech** [codestates/JOINUS-client#8]
## ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 신청자 목록 컴포넌트 틀 잡기

## TODO
- [x] 개발 환경 구축
- [x] (임시) 리덕스 초기 상태 / 리듀서 / 액션 등 세팅
- [x] 제작해야 할 컴포넌트 분류
- [x] Switch 라우팅 적용

## Estimated time
- `3h`

## Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `3-1`
- Urgency: `High`
